FROM node:24.13.1

COPY --from=denoland/deno:bin-2.6.9 /deno /usr/bin/deno

# CMD /usr/local/bin/npm ci && /usr/local/bin/node /app/src/server.js
CMD /usr/bin/deno install --allow-scripts && /usr/bin/deno --allow-all /app/src/server.js
